// Terminal configuration - themes and fonts

export interface TerminalTheme {
  id: string
  name: string
  background: string
  foreground: string
  cursor: string
  cursorAccent: string
  selectionBackground: string
  black: string
  red: string
  green: string
  yellow: string
  blue: string
  magenta: string
  cyan: string
  white: string
  brightBlack: string
  brightRed: string
  brightGreen: string
  brightYellow: string
  brightBlue: string
  brightMagenta: string
  brightCyan: string
  brightWhite: string
}

export interface TerminalFont {
  id: string
  name: string
  family: string
  isMonospace: boolean
  category: 'modern' | 'retro' | 'classic' | 'pixel'
}

export interface UIFont {
  id: string
  name: string
  family: string
  category: 'system' | 'sans' | 'serif' | 'display'
}

export interface SyntaxTheme {
  id: string
  name: string
  category: 'dark' | 'light'
}

// ============================================
// THEMES
// ============================================

export const TERMINAL_THEMES: TerminalTheme[] = [
  // Default (matches the app's native dialog style)
  {
    id: 'default',
    name: 'Default',
    background: '#0d1117',
    foreground: '#e6edf3',
    cursor: '#58a6ff',
    cursorAccent: '#0d1117',
    selectionBackground: 'rgba(88, 166, 255, 0.3)',
    black: '#161b22',
    red: '#f85149',
    green: '#3fb950',
    yellow: '#d29922',
    blue: '#58a6ff',
    magenta: '#bc8cff',
    cyan: '#39c5cf',
    white: '#8b949e',
    brightBlack: '#30363d',
    brightRed: '#ffa198',
    brightGreen: '#56d364',
    brightYellow: '#e3b341',
    brightBlue: '#79c0ff',
    brightMagenta: '#d2a8ff',
    brightCyan: '#56d4dd',
    brightWhite: '#f0f6fc',
  },
  // Tokyo Night
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    background: '#1a1b26',
    foreground: '#c0caf5',
    cursor: '#c0caf5',
    cursorAccent: '#1a1b26',
    selectionBackground: 'rgba(45, 212, 191, 0.3)',
    black: '#15161e',
    red: '#f7768e',
    green: '#9ece6a',
    yellow: '#e0af68',
    blue: '#7aa2f7',
    magenta: '#bb9af7',
    cyan: '#7dcfff',
    white: '#a9b1d6',
    brightBlack: '#414868',
    brightRed: '#f7768e',
    brightGreen: '#9ece6a',
    brightYellow: '#e0af68',
    brightBlue: '#7aa2f7',
    brightMagenta: '#bb9af7',
    brightCyan: '#7dcfff',
    brightWhite: '#c0caf5',
  },
  // Dracula
  {
    id: 'dracula',
    name: 'Dracula',
    background: '#282a36',
    foreground: '#f8f8f2',
    cursor: '#f8f8f2',
    cursorAccent: '#282a36',
    selectionBackground: 'rgba(68, 71, 90, 0.5)',
    black: '#21222c',
    red: '#ff5555',
    green: '#50fa7b',
    yellow: '#f1fa8c',
    blue: '#bd93f9',
    magenta: '#ff79c6',
    cyan: '#8be9fd',
    white: '#f8f8f2',
    brightBlack: '#6272a4',
    brightRed: '#ff6e6e',
    brightGreen: '#69ff94',
    brightYellow: '#ffffa5',
    brightBlue: '#d6acff',
    brightMagenta: '#ff92df',
    brightCyan: '#a4ffff',
    brightWhite: '#ffffff',
  },
  // Nord
  {
    id: 'nord',
    name: 'Nord',
    background: '#2e3440',
    foreground: '#d8dee9',
    cursor: '#d8dee9',
    cursorAccent: '#2e3440',
    selectionBackground: 'rgba(136, 192, 208, 0.3)',
    black: '#3b4252',
    red: '#bf616a',
    green: '#a3be8c',
    yellow: '#ebcb8b',
    blue: '#81a1c1',
    magenta: '#b48ead',
    cyan: '#88c0d0',
    white: '#e5e9f0',
    brightBlack: '#4c566a',
    brightRed: '#bf616a',
    brightGreen: '#a3be8c',
    brightYellow: '#ebcb8b',
    brightBlue: '#81a1c1',
    brightMagenta: '#b48ead',
    brightCyan: '#8fbcbb',
    brightWhite: '#eceff4',
  },
  // Gruvbox Dark
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    background: '#282828',
    foreground: '#ebdbb2',
    cursor: '#ebdbb2',
    cursorAccent: '#282828',
    selectionBackground: 'rgba(214, 93, 14, 0.3)',
    black: '#282828',
    red: '#cc241d',
    green: '#98971a',
    yellow: '#d79921',
    blue: '#458588',
    magenta: '#b16286',
    cyan: '#689d6a',
    white: '#a89984',
    brightBlack: '#928374',
    brightRed: '#fb4934',
    brightGreen: '#b8bb26',
    brightYellow: '#fabd2f',
    brightBlue: '#83a598',
    brightMagenta: '#d3869b',
    brightCyan: '#8ec07c',
    brightWhite: '#ebdbb2',
  },
  // One Dark
  {
    id: 'one-dark',
    name: 'One Dark',
    background: '#282c34',
    foreground: '#abb2bf',
    cursor: '#528bff',
    cursorAccent: '#282c34',
    selectionBackground: 'rgba(82, 139, 255, 0.3)',
    black: '#282c34',
    red: '#e06c75',
    green: '#98c379',
    yellow: '#e5c07b',
    blue: '#61afef',
    magenta: '#c678dd',
    cyan: '#56b6c2',
    white: '#abb2bf',
    brightBlack: '#5c6370',
    brightRed: '#e06c75',
    brightGreen: '#98c379',
    brightYellow: '#e5c07b',
    brightBlue: '#61afef',
    brightMagenta: '#c678dd',
    brightCyan: '#56b6c2',
    brightWhite: '#ffffff',
  },
  // Catppuccin Mocha
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    background: '#1e1e2e',
    foreground: '#cdd6f4',
    cursor: '#f5e0dc',
    cursorAccent: '#1e1e2e',
    selectionBackground: 'rgba(137, 180, 250, 0.3)',
    black: '#45475a',
    red: '#f38ba8',
    green: '#a6e3a1',
    yellow: '#f9e2af',
    blue: '#89b4fa',
    magenta: '#f5c2e7',
    cyan: '#94e2d5',
    white: '#bac2de',
    brightBlack: '#585b70',
    brightRed: '#f38ba8',
    brightGreen: '#a6e3a1',
    brightYellow: '#f9e2af',
    brightBlue: '#89b4fa',
    brightMagenta: '#f5c2e7',
    brightCyan: '#94e2d5',
    brightWhite: '#a6adc8',
  },
  // Solarized Dark
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    background: '#002b36',
    foreground: '#839496',
    cursor: '#839496',
    cursorAccent: '#002b36',
    selectionBackground: 'rgba(38, 139, 210, 0.3)',
    black: '#073642',
    red: '#dc322f',
    green: '#859900',
    yellow: '#b58900',
    blue: '#268bd2',
    magenta: '#d33682',
    cyan: '#2aa198',
    white: '#eee8d5',
    brightBlack: '#002b36',
    brightRed: '#cb4b16',
    brightGreen: '#586e75',
    brightYellow: '#657b83',
    brightBlue: '#839496',
    brightMagenta: '#6c71c4',
    brightCyan: '#93a1a1',
    brightWhite: '#fdf6e3',
  },
  // Monokai Pro
  {
    id: 'monokai-pro',
    name: 'Monokai Pro',
    background: '#2d2a2e',
    foreground: '#fcfcfa',
    cursor: '#fcfcfa',
    cursorAccent: '#2d2a2e',
    selectionBackground: 'rgba(255, 216, 102, 0.2)',
    black: '#403e41',
    red: '#ff6188',
    green: '#a9dc76',
    yellow: '#ffd866',
    blue: '#fc9867',
    magenta: '#ab9df2',
    cyan: '#78dce8',
    white: '#fcfcfa',
    brightBlack: '#727072',
    brightRed: '#ff6188',
    brightGreen: '#a9dc76',
    brightYellow: '#ffd866',
    brightBlue: '#fc9867',
    brightMagenta: '#ab9df2',
    brightCyan: '#78dce8',
    brightWhite: '#fcfcfa',
  },
  // GitHub Dark
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    background: '#0d1117',
    foreground: '#c9d1d9',
    cursor: '#58a6ff',
    cursorAccent: '#0d1117',
    selectionBackground: 'rgba(88, 166, 255, 0.3)',
    black: '#0d1117',
    red: '#f85149',
    green: '#3fb950',
    yellow: '#d29922',
    blue: '#58a6ff',
    magenta: '#bc8cff',
    cyan: '#39c5cf',
    white: '#8b949e',
    brightBlack: '#6e7681',
    brightRed: '#ffa198',
    brightGreen: '#56d364',
    brightYellow: '#e3b341',
    brightBlue: '#79c0ff',
    brightMagenta: '#d2a8ff',
    brightCyan: '#56d4dd',
    brightWhite: '#f0f6fc',
  },
  // Synthwave '84
  {
    id: 'synthwave-84',
    name: "Synthwave '84",
    background: '#262335',
    foreground: '#ffffff',
    cursor: '#ff7edb',
    cursorAccent: '#262335',
    selectionBackground: 'rgba(255, 126, 219, 0.3)',
    black: '#262335',
    red: '#fe4450',
    green: '#72f1b8',
    yellow: '#fede5d',
    blue: '#03edf9',
    magenta: '#ff7edb',
    cyan: '#03edf9',
    white: '#ffffff',
    brightBlack: '#614d85',
    brightRed: '#fe4450',
    brightGreen: '#72f1b8',
    brightYellow: '#f97e72',
    brightBlue: '#03edf9',
    brightMagenta: '#ff7edb',
    brightCyan: '#03edf9',
    brightWhite: '#ffffff',
  },
  // Cyberpunk
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    background: '#0a0a0f',
    foreground: '#00ff9c',
    cursor: '#ff00ff',
    cursorAccent: '#0a0a0f',
    selectionBackground: 'rgba(255, 0, 255, 0.3)',
    black: '#0a0a0f',
    red: '#ff003c',
    green: '#00ff9c',
    yellow: '#fffc58',
    blue: '#00b3ff',
    magenta: '#ff00ff',
    cyan: '#00ffff',
    white: '#d0d0d0',
    brightBlack: '#555555',
    brightRed: '#ff5577',
    brightGreen: '#55ffaa',
    brightYellow: '#ffff77',
    brightBlue: '#55aaff',
    brightMagenta: '#ff55ff',
    brightCyan: '#55ffff',
    brightWhite: '#ffffff',
  },
  // Retro Green (CRT)
  {
    id: 'retro-green',
    name: 'Retro Green (CRT)',
    background: '#0a0a0a',
    foreground: '#33ff33',
    cursor: '#33ff33',
    cursorAccent: '#0a0a0a',
    selectionBackground: 'rgba(51, 255, 51, 0.3)',
    black: '#0a0a0a',
    red: '#ff3333',
    green: '#33ff33',
    yellow: '#ffff33',
    blue: '#3333ff',
    magenta: '#ff33ff',
    cyan: '#33ffff',
    white: '#33ff33',
    brightBlack: '#1a1a1a',
    brightRed: '#ff5555',
    brightGreen: '#55ff55',
    brightYellow: '#ffff55',
    brightBlue: '#5555ff',
    brightMagenta: '#ff55ff',
    brightCyan: '#55ffff',
    brightWhite: '#55ff55',
  },
  // Retro Amber (CRT)
  {
    id: 'retro-amber',
    name: 'Retro Amber (CRT)',
    background: '#0a0800',
    foreground: '#ffb000',
    cursor: '#ffb000',
    cursorAccent: '#0a0800',
    selectionBackground: 'rgba(255, 176, 0, 0.3)',
    black: '#0a0800',
    red: '#ff5533',
    green: '#ffb000',
    yellow: '#ffcc00',
    blue: '#cc8800',
    magenta: '#ff8844',
    cyan: '#ffcc66',
    white: '#ffb000',
    brightBlack: '#1a1400',
    brightRed: '#ff7755',
    brightGreen: '#ffcc33',
    brightYellow: '#ffdd33',
    brightBlue: '#ddaa33',
    brightMagenta: '#ffaa66',
    brightCyan: '#ffdd88',
    brightWhite: '#ffcc33',
  },
  // Matrix
  {
    id: 'matrix',
    name: 'Matrix',
    background: '#000000',
    foreground: '#00ff00',
    cursor: '#00ff00',
    cursorAccent: '#000000',
    selectionBackground: 'rgba(0, 255, 0, 0.2)',
    black: '#000000',
    red: '#00aa00',
    green: '#00ff00',
    yellow: '#00dd00',
    blue: '#00bb00',
    magenta: '#00cc00',
    cyan: '#00ee00',
    white: '#00ff00',
    brightBlack: '#003300',
    brightRed: '#00cc00',
    brightGreen: '#00ff00',
    brightYellow: '#00ff00',
    brightBlue: '#00dd00',
    brightMagenta: '#00ee00',
    brightCyan: '#00ff00',
    brightWhite: '#00ff00',
  },
  // Horizon Dark
  {
    id: 'horizon-dark',
    name: 'Horizon Dark',
    background: '#1c1e26',
    foreground: '#d5d8da',
    cursor: '#e95678',
    cursorAccent: '#1c1e26',
    selectionBackground: 'rgba(233, 86, 120, 0.3)',
    black: '#16161c',
    red: '#e95678',
    green: '#29d398',
    yellow: '#fab795',
    blue: '#26bbd9',
    magenta: '#ee64ac',
    cyan: '#59e3e3',
    white: '#d5d8da',
    brightBlack: '#232530',
    brightRed: '#ec6a88',
    brightGreen: '#3fdaa4',
    brightYellow: '#fbc3a7',
    brightBlue: '#3fc6de',
    brightMagenta: '#f075b7',
    brightCyan: '#6be6e6',
    brightWhite: '#f0f0f0',
  },
  // Material Dark
  {
    id: 'material-dark',
    name: 'Material Dark',
    background: '#212121',
    foreground: '#eeffff',
    cursor: '#ffcc00',
    cursorAccent: '#212121',
    selectionBackground: 'rgba(128, 203, 196, 0.3)',
    black: '#212121',
    red: '#f07178',
    green: '#c3e88d',
    yellow: '#ffcb6b',
    blue: '#82aaff',
    magenta: '#c792ea',
    cyan: '#89ddff',
    white: '#eeffff',
    brightBlack: '#4a4a4a',
    brightRed: '#f78c6c',
    brightGreen: '#c3e88d',
    brightYellow: '#ffcb6b',
    brightBlue: '#82aaff',
    brightMagenta: '#c792ea',
    brightCyan: '#89ddff',
    brightWhite: '#ffffff',
  },
  // Ayu Dark
  {
    id: 'ayu-dark',
    name: 'Ayu Dark',
    background: '#0a0e14',
    foreground: '#b3b1ad',
    cursor: '#e6b450',
    cursorAccent: '#0a0e14',
    selectionBackground: 'rgba(230, 180, 80, 0.2)',
    black: '#01060e',
    red: '#ea6c73',
    green: '#91b362',
    yellow: '#f9af4f',
    blue: '#53bdfa',
    magenta: '#fae994',
    cyan: '#90e1c6',
    white: '#c7c7c7',
    brightBlack: '#686868',
    brightRed: '#f07178',
    brightGreen: '#c2d94c',
    brightYellow: '#ffb454',
    brightBlue: '#59c2ff',
    brightMagenta: '#ffee99',
    brightCyan: '#95e6cb',
    brightWhite: '#ffffff',
  },
  // Palenight
  {
    id: 'palenight',
    name: 'Palenight',
    background: '#292d3e',
    foreground: '#a6accd',
    cursor: '#ffcc00',
    cursorAccent: '#292d3e',
    selectionBackground: 'rgba(113, 124, 180, 0.3)',
    black: '#292d3e',
    red: '#f07178',
    green: '#c3e88d',
    yellow: '#ffcb6b',
    blue: '#82aaff',
    magenta: '#c792ea',
    cyan: '#89ddff',
    white: '#d0d0d0',
    brightBlack: '#434758',
    brightRed: '#ff8b92',
    brightGreen: '#ddffa7',
    brightYellow: '#ffe585',
    brightBlue: '#9cc4ff',
    brightMagenta: '#e1acff',
    brightCyan: '#a3f7ff',
    brightWhite: '#ffffff',
  },
  // Cobalt2
  {
    id: 'cobalt2',
    name: 'Cobalt2',
    background: '#193549',
    foreground: '#ffffff',
    cursor: '#ffc600',
    cursorAccent: '#193549',
    selectionBackground: 'rgba(255, 198, 0, 0.2)',
    black: '#000000',
    red: '#ff628c',
    green: '#a5ff90',
    yellow: '#ffc600',
    blue: '#0088ff',
    magenta: '#ff628c',
    cyan: '#80fcff',
    white: '#ffffff',
    brightBlack: '#555555',
    brightRed: '#ff9d9d',
    brightGreen: '#c5ffc4',
    brightYellow: '#ffe080',
    brightBlue: '#66b5ff',
    brightMagenta: '#ffb5c5',
    brightCyan: '#b5ffff',
    brightWhite: '#ffffff',
  },
  // Night Owl
  {
    id: 'night-owl',
    name: 'Night Owl',
    background: '#011627',
    foreground: '#d6deeb',
    cursor: '#80a4c2',
    cursorAccent: '#011627',
    selectionBackground: 'rgba(29, 60, 83, 0.99)',
    black: '#011627',
    red: '#ef5350',
    green: '#22da6e',
    yellow: '#addb67',
    blue: '#82aaff',
    magenta: '#c792ea',
    cyan: '#21c7a8',
    white: '#ffffff',
    brightBlack: '#575656',
    brightRed: '#ef5350',
    brightGreen: '#22da6e',
    brightYellow: '#ffeb95',
    brightBlue: '#82aaff',
    brightMagenta: '#c792ea',
    brightCyan: '#7fdbca',
    brightWhite: '#ffffff',
  },
  // Everforest Dark
  {
    id: 'everforest-dark',
    name: 'Everforest Dark',
    background: '#2d353b',
    foreground: '#d3c6aa',
    cursor: '#d3c6aa',
    cursorAccent: '#2d353b',
    selectionBackground: 'rgba(163, 190, 140, 0.3)',
    black: '#475258',
    red: '#e67e80',
    green: '#a7c080',
    yellow: '#dbbc7f',
    blue: '#7fbbb3',
    magenta: '#d699b6',
    cyan: '#83c092',
    white: '#d3c6aa',
    brightBlack: '#475258',
    brightRed: '#e67e80',
    brightGreen: '#a7c080',
    brightYellow: '#dbbc7f',
    brightBlue: '#7fbbb3',
    brightMagenta: '#d699b6',
    brightCyan: '#83c092',
    brightWhite: '#d3c6aa',
  },
  // Rose Pine
  {
    id: 'rose-pine',
    name: 'Rosé Pine',
    background: '#191724',
    foreground: '#e0def4',
    cursor: '#524f67',
    cursorAccent: '#191724',
    selectionBackground: 'rgba(110, 106, 134, 0.4)',
    black: '#26233a',
    red: '#eb6f92',
    green: '#31748f',
    yellow: '#f6c177',
    blue: '#9ccfd8',
    magenta: '#c4a7e7',
    cyan: '#ebbcba',
    white: '#e0def4',
    brightBlack: '#6e6a86',
    brightRed: '#eb6f92',
    brightGreen: '#31748f',
    brightYellow: '#f6c177',
    brightBlue: '#9ccfd8',
    brightMagenta: '#c4a7e7',
    brightCyan: '#ebbcba',
    brightWhite: '#e0def4',
  },
  // Kanagawa
  {
    id: 'kanagawa',
    name: 'Kanagawa',
    background: '#1f1f28',
    foreground: '#dcd7ba',
    cursor: '#c8c093',
    cursorAccent: '#1f1f28',
    selectionBackground: 'rgba(73, 72, 62, 0.5)',
    black: '#16161d',
    red: '#c34043',
    green: '#76946a',
    yellow: '#c0a36e',
    blue: '#7e9cd8',
    magenta: '#957fb8',
    cyan: '#6a9589',
    white: '#dcd7ba',
    brightBlack: '#727169',
    brightRed: '#e82424',
    brightGreen: '#98bb6c',
    brightYellow: '#e6c384',
    brightBlue: '#7fb4ca',
    brightMagenta: '#938aa9',
    brightCyan: '#7aa89f',
    brightWhite: '#dcd7ba',
  },
]

// ============================================
// FONTS
// ============================================

export const TERMINAL_FONTS: TerminalFont[] = [
  // Modern Monospace
  {
    id: 'jetbrains-mono',
    name: 'JetBrains Mono',
    family: '"JetBrains Mono", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'fira-code',
    name: 'Fira Code',
    family: '"Fira Code", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'cascadia-code',
    name: 'Cascadia Code',
    family: '"Cascadia Code", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'source-code-pro',
    name: 'Source Code Pro',
    family: '"Source Code Pro", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'ibm-plex-mono',
    name: 'IBM Plex Mono',
    family: '"IBM Plex Mono", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'hack',
    name: 'Hack',
    family: '"Hack", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'victor-mono',
    name: 'Victor Mono',
    family: '"Victor Mono", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'iosevka',
    name: 'Iosevka',
    family: '"Iosevka", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'monaspace-neon',
    name: 'Monaspace Neon',
    family: '"Monaspace Neon", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'monaspace-argon',
    name: 'Monaspace Argon',
    family: '"Monaspace Argon", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'geist-mono',
    name: 'Geist Mono',
    family: '"Geist Mono", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'commit-mono',
    name: 'Commit Mono',
    family: '"Commit Mono", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'recursive-mono',
    name: 'Recursive Mono',
    family: '"Recursive Mono", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'intel-one-mono',
    name: 'Intel One Mono',
    family: '"Intel One Mono", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'berkeley-mono',
    name: 'Berkeley Mono',
    family: '"Berkeley Mono", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'maple-mono',
    name: 'Maple Mono',
    family: '"Maple Mono", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: '0xproto',
    name: '0xProto',
    family: '"0xProto", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'julia-mono',
    name: 'JuliaMono',
    family: '"JuliaMono", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'fantasque-sans-mono',
    name: 'Fantasque Sans Mono',
    family: '"Fantasque Sans Mono", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'anonymous-pro',
    name: 'Anonymous Pro',
    family: '"Anonymous Pro", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'inconsolata',
    name: 'Inconsolata',
    family: '"Inconsolata", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'comic-mono',
    name: 'Comic Mono',
    family: '"Comic Mono", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'meslo',
    name: 'Meslo LG',
    family: '"Meslo LG M", "MesloLGM Nerd Font", monospace',
    isMonospace: true,
    category: 'modern',
  },
  {
    id: 'monocraft',
    name: 'Monocraft',
    family: '"Monocraft", monospace',
    isMonospace: true,
    category: 'pixel',
  },
  // Classic Monospace
  {
    id: 'sf-mono',
    name: 'SF Mono',
    family: '"SF Mono", monospace',
    isMonospace: true,
    category: 'classic',
  },
  {
    id: 'menlo',
    name: 'Menlo',
    family: '"Menlo", monospace',
    isMonospace: true,
    category: 'classic',
  },
  {
    id: 'monaco',
    name: 'Monaco',
    family: '"Monaco", monospace',
    isMonospace: true,
    category: 'classic',
  },
  {
    id: 'consolas',
    name: 'Consolas',
    family: '"Consolas", monospace',
    isMonospace: true,
    category: 'classic',
  },
  {
    id: 'courier-new',
    name: 'Courier New',
    family: '"Courier New", monospace',
    isMonospace: true,
    category: 'classic',
  },
  {
    id: 'andale-mono',
    name: 'Andale Mono',
    family: '"Andale Mono", monospace',
    isMonospace: true,
    category: 'classic',
  },
  {
    id: 'dejavu-sans-mono',
    name: 'DejaVu Sans Mono',
    family: '"DejaVu Sans Mono", monospace',
    isMonospace: true,
    category: 'classic',
  },
  {
    id: 'ubuntu-mono',
    name: 'Ubuntu Mono',
    family: '"Ubuntu Mono", monospace',
    isMonospace: true,
    category: 'classic',
  },
  {
    id: 'droid-sans-mono',
    name: 'Droid Sans Mono',
    family: '"Droid Sans Mono", monospace',
    isMonospace: true,
    category: 'classic',
  },
  {
    id: 'liberation-mono',
    name: 'Liberation Mono',
    family: '"Liberation Mono", monospace',
    isMonospace: true,
    category: 'classic',
  },
  // Retro / CRT Fonts
  {
    id: 'glass-tty-vt220',
    name: 'Glass TTY VT220',
    family: '"Glass TTY VT220", "VT323", monospace',
    isMonospace: true,
    category: 'retro',
  },
  {
    id: 'vt323',
    name: 'VT323',
    family: '"VT323", monospace',
    isMonospace: true,
    category: 'retro',
  },
  {
    id: 'ibm-3270',
    name: 'IBM 3270',
    family: '"IBM 3270", monospace',
    isMonospace: true,
    category: 'retro',
  },
  {
    id: 'terminus',
    name: 'Terminus',
    family: '"Terminus", "Terminus (TTF)", monospace',
    isMonospace: true,
    category: 'retro',
  },
  {
    id: 'profont',
    name: 'ProFont',
    family: '"ProFont", monospace',
    isMonospace: true,
    category: 'retro',
  },
  {
    id: 'fixedsys-excelsior',
    name: 'Fixedsys Excelsior',
    family: '"Fixedsys Excelsior", monospace',
    isMonospace: true,
    category: 'retro',
  },
  {
    id: 'px437-ibm-vga',
    name: 'PxPlus IBM VGA',
    family: '"PxPlus IBM VGA8", monospace',
    isMonospace: true,
    category: 'retro',
  },
  {
    id: 'dos-v',
    name: 'DOS/V',
    family: '"DOS/V re. JPN", monospace',
    isMonospace: true,
    category: 'retro',
  },
  {
    id: 'perfect-dos',
    name: 'Perfect DOS VGA',
    family: '"Perfect DOS VGA 437", monospace',
    isMonospace: true,
    category: 'retro',
  },
  {
    id: 'commodore-64',
    name: 'Commodore 64',
    family: '"C64 Pro Mono", monospace',
    isMonospace: true,
    category: 'retro',
  },
  {
    id: 'apple-ii',
    name: 'Apple II',
    family: '"Print Char 21", monospace',
    isMonospace: true,
    category: 'retro',
  },
  // Pixel Fonts
  {
    id: 'cozette',
    name: 'Cozette',
    family: '"Cozette", monospace',
    isMonospace: true,
    category: 'pixel',
  },
  {
    id: 'scientifica',
    name: 'Scientifica',
    family: '"Scientifica", monospace',
    isMonospace: true,
    category: 'pixel',
  },
  {
    id: 'envypn',
    name: 'Envy Code R',
    family: '"Envy Code R", monospace',
    isMonospace: true,
    category: 'pixel',
  },
  {
    id: 'creep',
    name: 'Creep',
    family: '"Creep", monospace',
    isMonospace: true,
    category: 'pixel',
  },
  {
    id: 'tamsyn',
    name: 'Tamsyn',
    family: '"Tamsyn", monospace',
    isMonospace: true,
    category: 'pixel',
  },
  {
    id: 'spleen',
    name: 'Spleen',
    family: '"Spleen", monospace',
    isMonospace: true,
    category: 'pixel',
  },
  {
    id: 'unscii',
    name: 'Unscii',
    family: '"Unscii", monospace',
    isMonospace: true,
    category: 'pixel',
  },
]

// ============================================
// UI FONTS (Sans-serif for app interface)
// ============================================

export const UI_FONTS: UIFont[] = [
  // System Fonts
  {
    id: 'system-ui',
    name: 'System Default',
    family: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    category: 'system',
  },
  {
    id: 'sf-pro',
    name: 'SF Pro',
    family: '"SF Pro Display", "SF Pro", system-ui, -apple-system, sans-serif',
    category: 'system',
  },
  {
    id: 'segoe-ui',
    name: 'Segoe UI',
    family: '"Segoe UI", system-ui, sans-serif',
    category: 'system',
  },
  // Modern Sans
  {
    id: 'inter',
    name: 'Inter',
    family: '"Inter", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'geist',
    name: 'Geist',
    family: '"Geist", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'plus-jakarta',
    name: 'Plus Jakarta Sans',
    family: '"Plus Jakarta Sans", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'dm-sans',
    name: 'DM Sans',
    family: '"DM Sans", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'space-grotesk',
    name: 'Space Grotesk',
    family: '"Space Grotesk", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'manrope',
    name: 'Manrope',
    family: '"Manrope", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'work-sans',
    name: 'Work Sans',
    family: '"Work Sans", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'nunito',
    name: 'Nunito',
    family: '"Nunito", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'poppins',
    name: 'Poppins',
    family: '"Poppins", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'outfit',
    name: 'Outfit',
    family: '"Outfit", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'sora',
    name: 'Sora',
    family: '"Sora", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'albert-sans',
    name: 'Albert Sans',
    family: '"Albert Sans", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'figtree',
    name: 'Figtree',
    family: '"Figtree", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'satoshi',
    name: 'Satoshi',
    family: '"Satoshi", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'cabinet-grotesk',
    name: 'Cabinet Grotesk',
    family: '"Cabinet Grotesk", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'general-sans',
    name: 'General Sans',
    family: '"General Sans", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'clash-display',
    name: 'Clash Display',
    family: '"Clash Display", system-ui, sans-serif',
    category: 'display',
  },
  // Classic Sans
  {
    id: 'roboto',
    name: 'Roboto',
    family: '"Roboto", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'lato',
    name: 'Lato',
    family: '"Lato", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'open-sans',
    name: 'Open Sans',
    family: '"Open Sans", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'montserrat',
    name: 'Montserrat',
    family: '"Montserrat", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'raleway',
    name: 'Raleway',
    family: '"Raleway", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'source-sans',
    name: 'Source Sans 3',
    family: '"Source Sans 3", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'ibm-plex-sans',
    name: 'IBM Plex Sans',
    family: '"IBM Plex Sans", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'fira-sans',
    name: 'Fira Sans',
    family: '"Fira Sans", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'ubuntu',
    name: 'Ubuntu',
    family: '"Ubuntu", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'karla',
    name: 'Karla',
    family: '"Karla", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'rubik',
    name: 'Rubik',
    family: '"Rubik", system-ui, sans-serif',
    category: 'sans',
  },
  {
    id: 'quicksand',
    name: 'Quicksand',
    family: '"Quicksand", system-ui, sans-serif',
    category: 'sans',
  },
  // Serif (for variety)
  {
    id: 'georgia',
    name: 'Georgia',
    family: '"Georgia", "Times New Roman", serif',
    category: 'serif',
  },
  {
    id: 'playfair',
    name: 'Playfair Display',
    family: '"Playfair Display", Georgia, serif',
    category: 'serif',
  },
  {
    id: 'merriweather',
    name: 'Merriweather',
    family: '"Merriweather", Georgia, serif',
    category: 'serif',
  },
  {
    id: 'lora',
    name: 'Lora',
    family: '"Lora", Georgia, serif',
    category: 'serif',
  },
  {
    id: 'libre-baskerville',
    name: 'Libre Baskerville',
    family: '"Libre Baskerville", Georgia, serif',
    category: 'serif',
  },
  {
    id: 'source-serif',
    name: 'Source Serif 4',
    family: '"Source Serif 4", Georgia, serif',
    category: 'serif',
  },
  {
    id: 'fraunces',
    name: 'Fraunces',
    family: '"Fraunces", Georgia, serif',
    category: 'serif',
  },
  // Display Fonts
  {
    id: 'orbitron',
    name: 'Orbitron',
    family: '"Orbitron", system-ui, sans-serif',
    category: 'display',
  },
  {
    id: 'audiowide',
    name: 'Audiowide',
    family: '"Audiowide", system-ui, sans-serif',
    category: 'display',
  },
  {
    id: 'exo-2',
    name: 'Exo 2',
    family: '"Exo 2", system-ui, sans-serif',
    category: 'display',
  },
  {
    id: 'rajdhani',
    name: 'Rajdhani',
    family: '"Rajdhani", system-ui, sans-serif',
    category: 'display',
  },
  {
    id: 'chakra-petch',
    name: 'Chakra Petch',
    family: '"Chakra Petch", system-ui, sans-serif',
    category: 'display',
  },
  {
    id: 'oxanium',
    name: 'Oxanium',
    family: '"Oxanium", system-ui, sans-serif',
    category: 'display',
  },
  {
    id: 'share-tech',
    name: 'Share Tech',
    family: '"Share Tech", system-ui, sans-serif',
    category: 'display',
  },
]

// ============================================
// SYNTAX THEMES (for code editor highlighting)
// ============================================

export const SYNTAX_THEMES: SyntaxTheme[] = [
  // Dark themes (installed CodeMirror themes)
  { id: 'oneDark', name: 'One Dark', category: 'dark' },
  { id: 'dracula', name: 'Dracula', category: 'dark' },
  { id: 'tokyoNight', name: 'Tokyo Night', category: 'dark' },
  { id: 'githubDark', name: 'GitHub Dark', category: 'dark' },
  { id: 'nord', name: 'Nord', category: 'dark' },
  // Light themes (installed CodeMirror themes)
  { id: 'githubLight', name: 'GitHub Light', category: 'light' },
]

// Default values
export const DEFAULT_THEME = TERMINAL_THEMES.find(t => t.id === 'default')!
export const DEFAULT_SYNTAX_THEME = SYNTAX_THEMES.find(t => t.id === 'oneDark')!
export const DEFAULT_FONT = TERMINAL_FONTS.find(f => f.id === 'jetbrains-mono')!
export const DEFAULT_UI_FONT = UI_FONTS.find(f => f.id === 'inter')!
export const DEFAULT_FONT_SIZE = 14

// Helper to convert theme to xterm.js format
export function themeToXterm(theme: TerminalTheme) {
  return {
    background: theme.background,
    foreground: theme.foreground,
    cursor: theme.cursor,
    cursorAccent: theme.cursorAccent,
    selectionBackground: theme.selectionBackground,
    black: theme.black,
    red: theme.red,
    green: theme.green,
    yellow: theme.yellow,
    blue: theme.blue,
    magenta: theme.magenta,
    cyan: theme.cyan,
    white: theme.white,
    brightBlack: theme.brightBlack,
    brightRed: theme.brightRed,
    brightGreen: theme.brightGreen,
    brightYellow: theme.brightYellow,
    brightBlue: theme.brightBlue,
    brightMagenta: theme.brightMagenta,
    brightCyan: theme.brightCyan,
    brightWhite: theme.brightWhite,
  }
}

// Helper to get subtle border color (20% opacity of white)
export function getSubtleBorder(theme: TerminalTheme): string {
  return `${theme.white}33`
}

// Helper to get hover border color (40% opacity of white)
export function getHoverBorder(theme: TerminalTheme): string {
  return `${theme.white}66`
}
